### ISSUE TITLE
Behaviour when multiple patterns match is undocumented or undefined.

### ISSUE THREAD

**Issue by AdrianRossouw** [rjrodger/patrun#8]
When multiple patterns exactly match the message, it is not clear what order they are executed in.

This is an issue with a library like seneca, where patterns are re-used consistently. The entity system is very prone to this, where you have many things being triggered by saving specific entities.

If all functions were idempotent you could maybe get away with it, but this leads to problems when they are all modifiying some form of shared state.

**Comment by AdrianRossouw** [comment]
I looked at the patch, and i don't see how it resolves this.

What I would like to know is :

```
p1.add({a:0},'P')
//  some code happens here
p1.add({a:0},'Q')
// some code happens here
p1.add({a:0},'R')
```

How does it choose which to return?
Does it return only the first, only the last, or an array of all of them.
If an array, is it ordered first to last or last to first?

**Comment by rjrodger** [comment]
just 'R' - matches are unique, so "there can be only one" match for {a:0}

i.e. last wins

**Comment by AdrianRossouw** [comment]
thanks richard, that's much clearer.
